name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: pwd && ls && cd ./screensy-rendezvous && docker build . --file Dockerfile --tag rendezvous:$(date +%s)
